---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: appointment-service
  name: appointment-service
spec:
  ports:
  - port: 8097
    protocol: TCP
    targetPort: 8097
  selector:
    app: appointment-service
  type: ClusterIP
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
  labels:
    app: appointment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
      - name: appointment-service
        image: ramesh1796/telecare:appointment-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8097
        
...
